### ISSUE TITLE
Add License.md

### ISSUE THREAD

**Issue by Anushka-shukla** [LoginRadius/go-sdk#2]
HI, Can I add License to this project ?

**Comment by indrasen715** [comment]
Hi @Anushka-shukla,

Thanks for bringing this to our notice and we appreciate your valuable feedback on this.

I will review this feedback with the team, and keep you posted on the progress.

Regards
Indrasen

**Comment by indrasen715** [comment]
HI @Anushka-shukla 

Thanks for your contribution to this project, this particular request is included in our latest releases.
Please let me know if you see any other areas of improvement. 

Regards
Indrasen
