### ISSUE TITLE
Total lack of useful documentation

### ISSUE THREAD

**Issue by daveschere** [LoginRadius/go-sdk#8]
There needs to be better use case documentation. The most obvious one would be how to validate an access token.

**Comment by indrasen715** [comment]
Hi @daveschere 

Thanks for your valuable feedback on this.

We will add the documentation with the Upcoming release, We have detailed documentation for this SDK on https://www.loginradius.com/docs/libraries/sdk-libraries/golang-library/ so you can refer to this document.

Please let me know if you see any other areas for improvement.

Regards

**Comment by indrasen715** [comment]
HI @daveschere 

Thanks for your contribution to this project, this particular request is included in our latest releases.
Please let me know if you see any other areas of improvement. 

Regards
Indrasen
